### ISSUE TITLE
Does not work, error: missing 1 required positional argument: 'backend'

### ISSUE THREAD

**Issue by ioogithub** [mossblaser/signal_for_android_decryption#1]
Here are the results after running the script:

```
$ python3 decrypt_backup.py /path/signal.backup  /path
Backup passphrase: 
Traceback (most recent call last):
  File "decrypt_backup.py", line 360, in <module>
    main()
  File "decrypt_backup.py", line 347, in main
    for _ in decrypt_backup(
  File "decrypt_backup.py", line 225, in decrypt_backup
    cipher_key, hmac_key = derive_keys(passphrase, salt)
  File "decrypt_backup.py", line 68, in derive_keys
    sha512 = Hash(algorithm=SHA512())
TypeError: __init__() missing 1 required positional argument: 'backend'
```

python3 --version
Python 3.8.10

$ pip install -r requirements.txt
```
Requirement already satisfied: protobuf in /home/oem/.local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (3.17.3)
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (2.8)
Requirement already satisfied: six>=1.9 in /usr/lib/python3/dist-packages (from protobuf->-r requirements.txt (line 1)) (1.14.0)
```

Is something missing?

**Comment by mossblaser** [comment]
Hmm... Curious... What version of the cryptography module do you have installed?

```python
>>> import cryptography
>>> print(cryptography.__version__)
```

Things work for me with cryptography 3.4.7 (sadly I only have Python 3.9 to hand, not 3.8 but I see no reason it should be any different).

(NB: There is an issue with recent versions of signal adding a new frame type which will cause my script to crash after decrypting the rest of your data successfully -- I intend to fix this but haven't got round to it yet!).

**Comment by mossblaser** [comment]
OK I've had chance to look into this and it seems that in [cryptography 3.1](https://cryptography.io/en/latest/changelog/#v3-1) the backend argument was made optional so I'm guessing you're using an older version.

Obviously this is my fault for not setting a suitable minimum version in the requirements.txt file but in any case I've pushed up a fix which should make this tool work with both newer and older versions of the library. Please reopen this issue if this doesn't do the trick!
